"""Adicionar data_de_nascimento na tabela usuarios

Revision ID: 20a4297d642e
Revises: 75ace46229f8
Create Date: 2025-11-10 20:23:50.705750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20a4297d642e"
down_revision: Union[str, Sequence[str], None] = "75ace46229f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usuarios", sa.Column("data_de_nascimento", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "data_de_nascimento")
    # ### end Alembic commands ###
